export const INSERT_CONFIG = "INSERT_CONFIG";
export const UPDATE_CONFIG = "UPDATE_CONFIG";
export const DELETE_FIELD = "DELETE_FIELD";
export const OPEN_PREVIEW = "OPEN_PREVIEW";
export const HANDLECHANGE='HANDLECHANGE';